language: node_js
node_js: 10
branches:
  only:
    - master
install:
  - yarn install
script:
  - yarn run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: docs/.vuepress/dist
  on:
    branch: master
